DefaultContentLanguage = "en" # Default language for multilingual sites

baseURL = "https://www.minutti.it/" # Your domain name. Must end with "/"
theme = "introduction" 
# disqusshortname                 = ""                     # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                     # https://gohugo.io/templates/internal/#google-analytics

[params]

dateFormat = "July 13, 1996" 
email = "matteo@minutti.it" # E-mail address for contact section

fadeIn = true # Turn on/off the fade-in effect
fadeInIndex = true # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off

favicon = "/img/fav.ico" # Path to favicon file
showRSSButton = false # Show rss button in navigation
themeStyle = "auto" # Choose "light" or "dark" or "auto"

# customCSS                  = ["overrides.css"]       # Include custom css files placed under assets/
# customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/
# plausible                  = true                    # Use Plausible analytics (requires an account at Plausible.io)

# Configure the home page
[params.home]
allPostsArchiveFormat = true # show all posts in an archive format
btc = "bc1q9jh5ulxl7cjm96sgt5kj6z8t7lp664aa5c8xc7" # BTC Address
# dash = "XkCAf2wBmhfM38onzqWNcTpbvppAy7nT2L" # DASH Address
# doge = "DNUdZt9AXLSG19YUGuVRkhHMyhGSwbLFtE" # DOGE Address
# xlm = "GCIIGBQEKZMEFFZRCUHVNPTJ6TLW3MMPYVFLXLAE3FKJ43E6GONPCARK" # XLM Address
introHeight = "fullheight" # Input either "medium" or "large" or "fullheight"
localTime = true # Show your current local time in contact section
numberOfProjectsToShow = 3 # Maximum number of projects to show on home page. Unset or comment out to show all projects
showAllPosts = false # Set true to list all posts on home page, or set false to link to separate blog list page
showLatest = true # Show latest blog post summary
timeFormat = "en-US" # Language specific format to use
timeZone = "Europe/Rome" # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

btcImg = "/img/btc.svg" # BTC gif
dogeImg = "/img/doge.svg" # DOGE gif
xlmImg = "/img/xlm.png" # DASH gif
# dashImg                  = "/img/dash.gif"         # DASH gif

aboutImg = "/img/dev.png"
[params.projects]
useTwoColumns = false # Use a layout with two columns instead of three

# Share buttons on blog post pages
[params.share]
facebook = true
pinterest = false
twitter = true

# Social icons appear in introduction and contact section. Add as many more as you like.
# Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
# Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free

[[params.social]]
icon = "linkedin-in" # icon name without the 'fa-'
icon_pack = "fab" 
url = "https://www.linkedin.com/in/matteo-minutti/" 

[[params.social]]
icon = "twitter" # icon name without the 'fa-'
icon_pack = "fab" 
url = "https://twitter.com/mntmtt" 

[[params.social]]
icon = "telegram" # icon name without the 'fa-'
icon_pack = "fab" 
url = "https://t.me/mntmtt" 

[[params.social]]
icon = "keybase" # icon name without the 'fa-'
icon_pack = "fab" 
url = "https://keybase.io/minutti" 

[[params.social]]
icon = "github-alt" # icon name without the 'fa-'
icon_pack = "fab" 
url = "https://github.com/backciro" 

[[params.social]]
icon = "envelope" # icon name without the 'fa-'
icon_pack = "fas" 
url = "mailto:matteo@minutti.it" # For a direct email link, use "mailto:test@example.org".

# If you don't want to use the default menu, you can define one by yourself

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
series = "series"
tag = "tags"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
# For styles, see https://xyproto.github.io/splash/docs/longer/all.html
style = "friendly"
tabWidth = 4

[languages]
[languages.en]
contentDir = "content/en"
languageCode = "en-us"
languageName = "English"
title = "Matteo Minutti"
weight = 0

[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
name = "Achievements"
url = "/#achievements"
weight = 2

[[languages.en.menu.main]]
name = "CV & Resume"
url = "/#cv"
weight = 3

#[[languages.en.menu.main]]
#    name    = "Blog"
#    url     = "/blog/"
#    weight  = 3   

[[languages.en.menu.main]]
name = "Contacts"
url = "/#contact"
weight = 4

[[languages.en.menu.main]]
name = "🇺🇸 -> 🇮🇹"
url = "/it/"
weight = 0

[languages.en.params]
description = "Matteo Minutti's Website" # Max 160 characters show in search results
footerText = "made with <span style=\"color:red\">♥</span> from an open-source developer" # Text to override default footer text (markdown allowed)

[languages.it]

contentDir = "content/it"
languageCode = "it"
languageName = "Italiano"
title = "Matteo Minutti"
weight = 1
[[languages.it.menu.main]]
name = "Home"
url = "/it/"
weight = 1

[[languages.it.menu.main]]
name = "Obiettivi"
url = "/it/#achievements"
weight = 2

[[languages.it.menu.main]]
name = "CV & Resume"
url = "/it/#cv"
weight = 3

#[[languages.it.menu.main]]
#    name    = "Blog"
#    url     = "/it/blog/"
#    weight  = 3   

[[languages.it.menu.main]]
name = "Contatti"
url = "/it/#contact"
weight = 4

[[languages.it.menu.main]]
name = "🇮🇹 -> 🇺🇸"
url = "/"
weight = 0

[languages.it.params]
description = "Matteo Minutti's Website"
footerText = "fatto col <span style=\"color:red\">♥</span> da uno sviluppatore open-source"
